[phases.setup]
nixPkgs = ["php82", "php82Extensions.redis", "php82Extensions.pdo_mysql", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.intl", "php82Extensions.opcache", "composer", "nodejs_20", "npm"]

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "composer install --optimize-autoloader --no-dev --no-interaction --no-progress"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
